bounds:
  rMC_slope: !!python/tuple
  - 0.01
  - 500.
  rMC_th: !!python/tuple
  - 0.01
  - 1.
  rCM_slope1: !!python/tuple
  - 0.01
  - 500.
  rCM_th1: !!python/tuple
  - 0.01
  - 1.
  rCM_peak1: !!python/tuple
  - 0.0001
  - 1.
  rCM_slope2: !!python/tuple
  - -100.
  - -0.001
  rCM_th2: !!python/tuple
  - 0.01
  - 1.
  rCM_min2: !!python/tuple
  - 0.
  - 1.
  rMC0: !!python/tuple
  - 0.1
  - 10.
  rCM0: !!python/tuple
  - 0.1
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 4000.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 3000.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
  # global_signal_decay: 161.81965512863673
  # global_signal_rise: 50.344024212982561
  # local_signal_decay: 1184.66706065663745
  # local_signal_rise: 42.740907646745779
  # rMC_slope: 9.6248528728378151
  # rMC_th: 0.12672325366569678
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
- - optimize_BTSP2_CA1_v9c
  - update_model_params
get_features_stages:
- source: optimize_BTSP2_CA1_v9c
  get_args_static: get_args_static_signal_amplitudes
  compute_features_shared: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_BTSP2_CA1_v9c
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
- source: optimize_BTSP2_CA1_v9c
  get_args_dynamic: get_args_dynamic_self_consistent_model_ramp
  compute_features: compute_features_self_consistent_model_ramp
  filter_features: filter_features_self_consistent_model_ramp
get_objectives:
  optimize_BTSP2_CA1_v9c: get_objectives
kwargs:
  data_file_name: '20180124_BTSP2_CA1_data.hdf5'
  verbose: 1
  min_delta_weight: -0.2
  data_keys:
objective_names:
- spont_residuals
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_residuals
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_residuals
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
- self_consistent_residuals
- weights_smoothness
- r_depot_smoothness
optimization_title: bidirectional_BTSP
param_gen: PopulationAnnealing
param_names:
- rMC_slope
- rMC_th
- rCM_slope1
- rCM_th1
- rCM_peak1
- rCM_slope2
- rCM_th2
- rCM_min2
- rMC0
- rCM0
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  spont_residuals: 0.5
  spont_delta_amp: 0.01
  spont_delta_width: 0.1
  spont_delta_peak_shift: 0.1
  spont_delta_asymmetry: 0.01
  spont_delta_min_loc: 0.1
  spont_delta_min_val: 0.01
  exp1_residuals: 0.5
  exp1_delta_amp: 0.01
  exp1_delta_width: 0.1
  exp1_delta_peak_shift: 0.1
  exp1_delta_asymmetry: 0.01
  exp1_delta_min_loc: 0.1
  exp1_delta_min_val: 0.01
  exp2_residuals: 0.5
  exp2_delta_amp: 0.01
  exp2_delta_width: 0.1
  exp2_delta_peak_shift: 0.1
  exp2_delta_asymmetry: 0.01
  exp2_delta_min_loc: 0.1
  exp2_delta_min_val: 0.01
  self_consistent_residuals: 0.5
  weights_smoothness: 0.01
  r_depot_smoothness: 0.00001
target_val:
  spont_residuals: 0.
  spont_delta_amp: 0.
  spont_delta_width: 0.
  spont_delta_peak_shift: 0.
  spont_delta_asymmetry: 0.
  spont_delta_min_loc: 0.
  spont_delta_min_val: 0.
  exp1_residuals: 0.
  exp1_delta_amp: 0.
  exp1_delta_width: 0.
  exp1_delta_peak_shift: 0.
  exp1_delta_asymmetry: 0.
  exp1_delta_min_loc: 0.
  exp1_delta_min_val: 0.
  exp2_residuals: 0.
  exp2_delta_amp: 0.
  exp2_delta_width: 0.
  exp2_delta_peak_shift: 0.
  exp2_delta_asymmetry: 0.
  exp2_delta_min_loc: 0.
  exp2_delta_min_val: 0.
  self_consistent_residuals: 0.
  weights_smoothness: 0.
  r_depot_smoothness: 0.
x0:
#  global_signal_decay: 161.81965512863673
#  global_signal_rise: 50.344024212982561
#  local_signal_decay: 1184.66706065663745
#  local_signal_rise: 42.740907646745779
#  rMC_slope: 9.6248528728378151
#  rMC_th: 0.12672325366569678
#  peak_delta_weight: 2.3766087807470182
#  rCM0: 2.2380142954546014
#  rCM_min2: 0.42442063289794074
#  rCM_peak1: 0.23285469603360878
#  rCM_slope1: 81.778112287913387
#  rCM_slope2: -1.6455405178536719
#  rCM_th1: 0.1397787027838677
#  rCM_th2: 0.78382164301093582
#  rMC0: 7.7357671268444506
  rMC_slope: 9.625000
  rMC_th: 0.126700
  rCM_slope1: 1.625000
  rCM_th1: 0.307900
  rCM_peak1: 0.073540
  rCM_slope2: -8.731000
  rCM_th2: 0.673000
  rCM_min2: 0.151300
  rMC0: 2.108000
  rCM0: 1.026000
  local_signal_rise: 42.740908
  local_signal_decay: 1185.000000
  global_signal_rise: 50.340000
  global_signal_decay: 161.800000
  peak_delta_weight: 3.768000