bounds:
  rMC_slope: !!python/tuple
  - 0.1
  - 100.
  rMC_th: !!python/tuple
  - 0.001
  - 1.
  rMC0: !!python/tuple
  - 0.1
  - 10.
  rCM0: !!python/tuple
  - 0.1
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 4000.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 3000.
  rCM_rise: !!python/tuple
  - 0.000001
  - 0.005
  rCM_decay: !!python/tuple
  - 0.0001
  - 0.5
  rCM_k: !!python/tuple
  - 1.
  - 5.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - rCM_decay
  - '>'
  - 1.0
  - rCM_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
  optimize_BTSP2_CA1_v6: update_model_params
get_features_stages:
- source: optimize_BTSP2_CA1_v6
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_BTSP2_CA1_v6
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
- source: optimize_BTSP2_CA1_v6
  get_args_dynamic: get_args_dynamic_self_consistent_model_ramp
  compute_features: compute_features_self_consistent_model_ramp
  filter_features: filter_features_self_consistent_model_ramp
get_objectives:
  optimize_BTSP2_CA1_v6: get_objectives
kwargs:
  data_file_name: '20180124_BTSP2_CA1_data.hdf5'
  verbose: 1
  min_delta_weight: -0.1
  data_keys:
    - !!python/tuple
      - 5
      - 1
    - !!python/tuple
      - 5
      - 2
objective_names:
- spont_residuals
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_residuals
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_residuals
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
- self_consistent_residuals
- smoothness
optimization_title: bidirectional_BTSP
param_gen: PopulationAnnealing
param_names:
- rMC_slope
- rMC_th
- rMC0
- rCM0
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- rCM_rise
- rCM_decay
- rCM_k
- peak_delta_weight
target_range:
  spont_residuals: 1.
  spont_delta_amp: 0.01
  spont_delta_width: 0.1
  spont_delta_peak_shift: 0.1
  spont_delta_asymmetry: 0.01
  spont_delta_min_loc: 0.1
  spont_delta_min_val: 0.01
  exp1_residuals: 1.
  exp1_delta_amp: 0.01
  exp1_delta_width: 0.1
  exp1_delta_peak_shift: 0.1
  exp1_delta_asymmetry: 0.01
  exp1_delta_min_loc: 0.1
  exp1_delta_min_val: 0.01
  exp2_residuals: 1.
  exp2_delta_amp: 0.01
  exp2_delta_width: 0.1
  exp2_delta_peak_shift: 0.1
  exp2_delta_asymmetry: 0.01
  exp2_delta_min_loc: 0.1
  exp2_delta_min_val: 0.01
  self_consistent_residuals: 1.
  smoothness: 0.01
target_val:
  spont_residuals: 0.
  spont_delta_amp: 0.
  spont_delta_width: 0.
  spont_delta_peak_shift: 0.
  spont_delta_asymmetry: 0.
  spont_delta_min_loc: 0.
  spont_delta_min_val: 0.
  exp1_residuals: 0.
  exp1_delta_amp: 0.
  exp1_delta_width: 0.
  exp1_delta_peak_shift: 0.
  exp1_delta_asymmetry: 0.
  exp1_delta_min_loc: 0.
  exp1_delta_min_val: 0.
  exp2_residuals: 0.
  exp2_delta_amp: 0.
  exp2_delta_width: 0.
  exp2_delta_peak_shift: 0.
  exp2_delta_asymmetry: 0.
  exp2_delta_min_loc: 0.
  exp2_delta_min_val: 0.
  self_consistent_residuals: 0.
  smoothness: 0.
x0:
  rMC_slope: 16.263512
  rMC_th: 0.094992
  rMC0: 1.857514
  rCM0: 0.254882
  local_signal_rise: 145.650408
  local_signal_decay: 481.339660
  global_signal_rise: 73.565365
  global_signal_decay: 73.998686
  rCM_rise: 0.003167
  rCM_decay: 0.115786
  rCM_k: 4.784573
  peak_delta_weight: 1.992888