bounds:
  rMC_slope: !!python/tuple
  - 0.1
  - 100.
  rMC_th: !!python/tuple
  - 0.
  - 1.
  rMC0: !!python/tuple
  - 0.1
  - 100.
  rCM0: !!python/tuple
  - 0.001
  - 100.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 4000.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 3000.
  rCM_rise: !!python/tuple
  - 0.000001
  - 0.005
  rCM_decay: !!python/tuple
  - 0.0001
  - 0.5
  rCM_k: !!python/tuple
  - 1.
  - 5.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - rCM_decay
  - '>'
  - 1.0
  - rCM_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
feature_names:
- spont_residuals
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_residuals
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_residuals
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
  optimize_BTSP2_CA1_v5: update_model_params
get_features_stages:
- source: optimize_BTSP2_CA1_v5
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_BTSP2_CA1_v5
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_BTSP2_CA1_v5: get_objectives
kwargs:
  data_file_name: '101017_BTSP_CA1_data.hdf5'
  verbose: False
  data_keys:
    - !!python/tuple
      - 1
      - 1
    - !!python/tuple
      - 1
      - 2
objective_names:
- spont_residuals
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_residuals
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_residuals
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
optimization_title: bidirectional_BTSP
param_gen: PopulationAnnealing
param_names:
- rMC_slope
- rMC_th
- rMC0
- rCM0
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- rCM_rise
- rCM_decay
- rCM_k
- peak_delta_weight
target_range:
  spont_residuals: 1.
  spont_delta_amp: 0.01
  spont_delta_width: 0.1
  spont_delta_peak_shift: 0.1
  spont_delta_asymmetry: 0.01
  spont_delta_min_loc: 0.1
  spont_delta_min_val: 0.01
  exp1_residuals: 1.
  exp1_delta_amp: 0.01
  exp1_delta_width: 0.1
  exp1_delta_peak_shift: 0.1
  exp1_delta_asymmetry: 0.01
  exp1_delta_min_loc: 0.1
  exp1_delta_min_val: 0.01
  exp2_residuals: 1.
  exp2_delta_amp: 0.01
  exp2_delta_width: 0.1
  exp2_delta_peak_shift: 0.1
  exp2_delta_asymmetry: 0.01
  exp2_delta_min_loc: 0.1
  exp2_delta_min_val: 0.01
target_val:
  spont_residuals: 0.
  spont_delta_amp: 0.
  spont_delta_width: 0.
  spont_delta_peak_shift: 0.
  spont_delta_asymmetry: 0.
  spont_delta_min_loc: 0.
  spont_delta_min_val: 0.
  exp1_residuals: 0.
  exp1_delta_amp: 0.
  exp1_delta_width: 0.
  exp1_delta_peak_shift: 0.
  exp1_delta_asymmetry: 0.
  exp1_delta_min_loc: 0.
  exp1_delta_min_val: 0.
  exp2_residuals: 0.
  exp2_delta_amp: 0.
  exp2_delta_width: 0.
  exp2_delta_peak_shift: 0.
  exp2_delta_asymmetry: 0.
  exp2_delta_min_loc: 0.
  exp2_delta_min_val: 0.
x0:
  rMC_slope: 10.
  rMC_th: 0.5
  rMC0: 99.
  rCM0: 8.080749
  local_signal_rise: 47.528376
  local_signal_decay: 2378.771733
  global_signal_rise: 45.710971
  global_signal_decay: 2748.063304
  rCM_rise: 0.002270
  rCM_decay: 0.142682
  rCM_k: 1.652937
  peak_delta_weight: 2.284682
