bounds:
  r_pot_slope: !!python/tuple
  - 0.01
  - 500.
  r_pot_th: !!python/tuple
  - 0.01
  - 1.
  r_depot_slope1: !!python/tuple
  - 0.01
  - 500.
  r_depot_th1: !!python/tuple
  - 0.01
  - 1.
  r_depot_xpeak1: !!python/tuple
  - 0.0001
  - 1.
  r_depot_slope2: !!python/tuple
  - -100.
  - -0.001
  r_depot_th2: !!python/tuple
  - 0.01
  - 1.
  r_depot_min2: !!python/tuple
  - 0.
  - 1.
  r_pot_k: !!python/tuple
  - 0.1
  - 10.
  r_depot_k: !!python/tuple
  - 0.1
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 4000.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 3000.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
  global_signal_decay: 161.81965512863673
  global_signal_rise: 50.344024212982561
  local_signal_decay: 1184.66706065663745
  local_signal_rise: 42.740907646745779
  # r_pot_slope: 9.6248528728378151
  # r_pot_th: 0.12672325366569678
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
  optimize_BTSP2_CA1_v10: update_model_params
get_features_stages:
- source: optimize_BTSP2_CA1_v10
  get_args_static: get_args_static_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
- source: optimize_BTSP2_CA1_v10
  get_args_dynamic: get_args_dynamic_self_consistent_model_ramp
  compute_features: compute_features_self_consistent_model_ramp
  filter_features: filter_features_self_consistent_model_ramp
get_objectives:
  optimize_BTSP2_CA1_v10: get_objectives
kwargs:
  data_file_name: '20180329_BTSP2_CA1_data.hdf5'
  verbose: 1
  min_delta_weight: -0.2
  data_keys:
objective_names:
- spont_residuals
- spont_delta_amp
# - spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_residuals
- exp1_delta_amp
# - exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_residuals
- exp2_delta_amp
# - exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
- self_consistent_residuals
- weights_smoothness
- r_depot_smoothness
optimization_title: bidirectional_BTSP
param_gen: PopulationAnnealing
param_names:
- r_pot_slope
- r_pot_th
- r_depot_slope1
- r_depot_th1
- r_depot_xpeak1
- r_depot_slope2
- r_depot_th2
- r_depot_min2
- r_pot_k
- r_depot_k
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  spont_residuals: 1.
  spont_delta_amp: 0.01
  spont_delta_width: 0.1
  spont_delta_peak_shift: 0.1
  spont_delta_asymmetry: 0.01
  spont_delta_min_loc: 0.1
  spont_delta_min_val: 0.01
  exp1_residuals: 1.
  exp1_delta_amp: 0.01
  exp1_delta_width: 0.1
  exp1_delta_peak_shift: 0.1
  exp1_delta_asymmetry: 0.01
  exp1_delta_min_loc: 0.1
  exp1_delta_min_val: 0.01
  exp2_residuals: 1.
  exp2_delta_amp: 0.01
  exp2_delta_width: 0.1
  exp2_delta_peak_shift: 0.1
  exp2_delta_asymmetry: 0.01
  exp2_delta_min_loc: 0.1
  exp2_delta_min_val: 0.01
  self_consistent_residuals: 1.
  weights_smoothness: 0.01
  r_depot_smoothness: 0.001
target_val:
  spont_residuals: 0.
  spont_delta_amp: 0.
  # spont_delta_width: 0.
  spont_delta_peak_shift: 0.
  spont_delta_asymmetry: 0.
  spont_delta_min_loc: 0.
  spont_delta_min_val: 0.
  exp1_residuals: 0.
  exp1_delta_amp: 0.
  # exp1_delta_width: 0.
  exp1_delta_peak_shift: 0.
  exp1_delta_asymmetry: 0.
  exp1_delta_min_loc: 0.
  exp1_delta_min_val: 0.
  exp2_residuals: 0.
  exp2_delta_amp: 0.
  # exp2_delta_width: 0.
  exp2_delta_peak_shift: 0.
  exp2_delta_asymmetry: 0.
  exp2_delta_min_loc: 0.
  exp2_delta_min_val: 0.
  self_consistent_residuals: 0.
  weights_smoothness: 0.
  r_depot_smoothness: 0.
x0:
#  global_signal_decay: 161.81965512863673
#  global_signal_rise: 50.344024212982561
#  local_signal_decay: 1184.66706065663745
#  local_signal_rise: 42.740907646745779
#  r_pot_slope: 9.6248528728378151
#  r_pot_th: 0.12672325366569678
#  peak_delta_weight: 2.3766087807470182
#  r_depot_k: 2.2380142954546014
#  r_depot_min2: 0.42442063289794074
#  r_depot_xpeak1: 0.23285469603360878
#  r_depot_slope1: 81.778112287913387
#  r_depot_slope2: -1.6455405178536719
#  r_depot_th1: 0.1397787027838677
#  r_depot_th2: 0.78382164301093582
#  r_pot_k: 7.7357671268444506
  r_pot_slope: 9.625000
  r_pot_th: 0.126700
  r_depot_slope1: 1.625000
  r_depot_th1: 0.307900
  r_depot_xpeak1: 0.073540
  r_depot_slope2: -8.731000
  r_depot_th2: 0.673000
  r_depot_min2: 0.151300
  r_pot_k: 2.108000
  r_depot_k: 1.026000
  local_signal_rise: 42.740908
  local_signal_decay: 1185.000000
  global_signal_rise: 50.340000
  global_signal_decay: 161.800000
  peak_delta_weight: 3.768000